server:
  port: 8083
  servlet:
    context-path: /kotlin/api

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=VERIFICATION_DB
    username: sa
    password: makeitso
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
